server:
  port: 8081

spring:
  mvc:
    problemdetails:
      enabled: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: petrifica-loan
      auto-index-creation: true


  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8080/realms/petrifica


  kafka:
    bootstrap-servers: localhost:9092

kafka:
  topic: loan-topic
  consumer:
    group-id: loan-group
    fraud-topic: fraud-topic

mongock:
  migration-scan-package:
    - com.marcelo.loan.migration
