server:
  port: 8082

spring:
  mvc:
    problemdetails:
      enabled: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: petrifica

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8080/realms/petrifica

  kafka:
    bootstrap-servers: localhost:9092

kafka:
  topic: fraud-topic
  group: fraud-group
